version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
    gosec:
      excludes:
        - G101
        - G107
        - G115
        - G404
      confidence: medium
    revive:
      enable-all-rules: true
      # See the rule descriptions here: https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
      rules:
        - name: add-constant # TODO: Should probably be removed, but needs to not care about tests
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity # TODO: Maybe code smell?
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: confusing-results
          disabled: true
        - name: cyclomatic # TODO: Maybe code smell?
          disabled: true
        - name: deep-exit # TODO: Not a big problem, but is only here because of log fatal in genesis stuff, should remove
          disabled: true
        - name: function-length # TODO: Maybe code smell?
          disabled: true
        - name: flag-parameter # TODO: This seems like a code smell, we should consider cleaning this up eventually
          disabled: true
        - name: function-result-limit # TODO: Maybe code smell
          disabled: true
        - name: line-length-limit # TODO: Probably OK, but could this be a code smell if set high enough?
          disabled: true
        - name: max-public-structs # TODO: Might be a code smell, investigate
          disabled: true
        - name: modifies-value-receiver # TODO: Seems bad, should remove
          disabled: true
        - name: redundant-import-alias # TODO: Code smell, no?
          disabled: true
        - name: unhandled-error
          disabled: false
          arguments: # Disable for these ones only
            - fmt.Printf
            - fmt.Print
            - fmt.Println
            - myFunction
        - name: unused-parameter # TODO: Should be checked, why do we need this exactly?
          disabled: true

          # TODO: REMOVE LIST
        - name: early-return
          disabled: true
          # TODO: END REMOVE LIST
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: differs only by capitalization to method
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - gosec
        text: 'G115: integer overflow conversion'
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - gosec
        text: 'G115: integer overflow conversion'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/cosmos/ibc-go)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
